name: null

channels:
  - intel
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - gh
  - git
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - panel
  - pip
  - python=3.7
  - python-language-server
  - scikit-learn
  - scipy
  - xgboost